# Numpy
-------

# What is NumPy?

1. NumPy stands for Numerical Python.
2. NumPy is a Python library used for working with arrays.
3. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

# Why Use NumPy?

1. In Python we have lists that serve the purpose of arrays, but they are slow to process.
2. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
3. The array object in NumPy is called ndarray

# Why is NumPy Faster Than Lists?

1. NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

# Install Depandancy for Numpy in your CMD

pip install numpy

In [1]:
import numpy

In [2]:
a = [0, 1, 2, 3, 4, 5]

print(a, type(a))

[0, 1, 2, 3, 4, 5] <class 'list'>


In [3]:
# Single Dimentional Array

a = numpy.array(a)

print(a, type(a))

[0 1 2 3 4 5] <class 'numpy.ndarray'>


In [21]:
b = [[1, 2], [3, 4]]

print(b, type(b))

[[1, 2], [3, 4]] <class 'list'>


In [22]:
# Two Dimentional Array

b = numpy.array(b)

print(b, type(b))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


# Arange :

1. Return evenly spaced values within a given interval.

In [9]:
import numpy as np

a = np.arange(0, 10)

print(a)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
a = np.arange(1, 10, 2)

print(a)

[1 6]


# Linspace :

1. Return evenly spaced numbers over a specified interval.

In [16]:
import numpy as np

a = np.linspace(0, 50, 5, dtype=int)

print(a)

[ 0 12 25 37 50]
